define ([],function() {
	return {
		gameGoal: "The goal of Pro Football 2.0 is to run, pass or return the ball from one end of the field (the right side) to the other (the left side). In keeping with the original Mattel Pro Football 2 game, the only a 10 yard section of the field is visible at one time. Before the ball is snapped 7 yards ahead and 3 yards behind the line of scrimage are visible. Advancing the ball more than 7 yards causes the player to wrap around the screen. The visible portion of the field is now 10 yards closer to the end zone.",
		playerRole: "As the player you are assuming the role of the quarterback. It is your job to run or pass to advance the football. Every play is a 'passing' player but the quarterback always has the option of running at any time before the ball is thrown. If you do throw a pass it can either be completed, not completed or intercepted. If the pass is completed the player then takes control of the wide receiver and attempts to advance the ball as far as possible. The player has 4 downs to advance the ball 10 yards. Failure to do so causes the player's team to lose posession of the ball.",
		receiverRole: "The wide receiver runs pass routes for the player. The receiver lines up on the left or right side of the quarterback at random and then runs a random route. This receiver is sure handed and will always catch your passes, if they are on target. On crossing and drag routes be sure to lead the reciever as it takes time for the football to reach him! If a defender is between the receiver and the player the pass will be intercepted. The exception to this rule is if the defender has crossed the line of scrimage. In this case the ball will be thrown over the defender.",
		defenderRole: "The defender is attempting to stop the player from advancing the ball. This can be done by 'bumping' into the player to tackle him or intercepting the player's passes. Each defender has a different role and different movement speeds. The LDE, DT and RDE attempts to contain the player and tackle him before he can throw the ball. The LB has a faster movement speed and attempts to guess the receiver's route by moving between him and the player. The FS and CB have the fastest movement speeds and attempt to tackle the receiver after the pass has been completed.",
		clockRole: "The game clock controls the length of the game. The game lasts for 6 minutes of game time. The clock is always running while the ball is in play. After a play is over the clock stops running. Kicking a field goal results in a 5 second runoff. The game ends when the play during which the clock hit zero is over.",
		scoringSystem: "In Pro Football 2.0 the player is always on offense. A touchdown is worth 7 points and a field goal is worth 3 points. However to make things fair for the defenders they can score points by stopping the player. An interception is worth 4 points, a turnover on downs is worth 4 points and a sack is worth 2 points. The team with the most points wins!"
	}
});